### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by jbarlow83** [pikepdf/pikepdf#13]
- [x] Deprecated (?) .metadata and add .docinfo and .xmp 
- [x] Support python-xmp-toolkit for metadata access
- [ ] PDF attachments should be removable or attachment API should be marked experimental
- [ ] Add page to Form XObject, for page merging
- [ ] Make pikepdf.String a little more friendly, perhaps, since it's irritating
- [x] Use .Name more consistently

Probably deferring:
- [ ] Maybe bookmarks?
- [ ] Change _methods.py to do direct subclassing, it's pretty much the same thing
